/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnlineSafetyRouteImport } from './routes/online-safety'
import { Route as ItSkillscopyRouteImport } from './routes/hardware-software'
import { Route as ItSkillsRouteImport } from './routes/it-skills'
import { Route as AlgorithmsRouteImport } from './routes/algorithms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnlineSafetySocialCreditRouteImport } from './routes/online-safety/social-credit'
import { Route as OnlineSafetyPhishingRouteImport } from './routes/online-safety/phishing'
import { Route as ItSkillsMouseSkillsRouteImport } from './routes/it-skills/mouse-skills'
import { Route as ItSkillsFileSimulationRouteImport } from './routes/it-skills/file-simulation'
import { Route as HardwareSoftwareInputOutputRouteImport } from './routes/hardware-software/input-output'

const OnlineSafetyRoute = OnlineSafetyRouteImport.update({
  id: '/online-safety',
  path: '/online-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ItSkillscopyRoute = ItSkillscopyRouteImport.update({
  id: '/it-skills copy',
  path: '/it-skills copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ItSkillsRoute = ItSkillsRouteImport.update({
  id: '/it-skills',
  path: '/it-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsRoute = AlgorithmsRouteImport.update({
  id: '/algorithms',
  path: '/algorithms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineSafetySocialCreditRoute =
  OnlineSafetySocialCreditRouteImport.update({
    id: '/social-credit',
    path: '/social-credit',
    getParentRoute: () => OnlineSafetyRoute,
  } as any)
const OnlineSafetyPhishingRoute = OnlineSafetyPhishingRouteImport.update({
  id: '/phishing',
  path: '/phishing',
  getParentRoute: () => OnlineSafetyRoute,
} as any)
const ItSkillsMouseSkillsRoute = ItSkillsMouseSkillsRouteImport.update({
  id: '/mouse-skills',
  path: '/mouse-skills',
  getParentRoute: () => ItSkillsRoute,
} as any)
const ItSkillsFileSimulationRoute = ItSkillsFileSimulationRouteImport.update({
  id: '/file-simulation',
  path: '/file-simulation',
  getParentRoute: () => ItSkillsRoute,
} as any)
const HardwareSoftwareInputOutputRoute =
  HardwareSoftwareInputOutputRouteImport.update({
    id: '/hardware-software/input-output',
    path: '/hardware-software/input-output',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/it-skills': typeof ItSkillsRouteWithChildren
  '/it-skills copy': typeof ItSkillscopyRoute
  '/online-safety': typeof OnlineSafetyRouteWithChildren
  '/hardware-software/input-output': typeof HardwareSoftwareInputOutputRoute
  '/it-skills/file-simulation': typeof ItSkillsFileSimulationRoute
  '/it-skills/mouse-skills': typeof ItSkillsMouseSkillsRoute
  '/online-safety/phishing': typeof OnlineSafetyPhishingRoute
  '/online-safety/social-credit': typeof OnlineSafetySocialCreditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/it-skills': typeof ItSkillsRouteWithChildren
  '/it-skills copy': typeof ItSkillscopyRoute
  '/online-safety': typeof OnlineSafetyRouteWithChildren
  '/hardware-software/input-output': typeof HardwareSoftwareInputOutputRoute
  '/it-skills/file-simulation': typeof ItSkillsFileSimulationRoute
  '/it-skills/mouse-skills': typeof ItSkillsMouseSkillsRoute
  '/online-safety/phishing': typeof OnlineSafetyPhishingRoute
  '/online-safety/social-credit': typeof OnlineSafetySocialCreditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/it-skills': typeof ItSkillsRouteWithChildren
  '/it-skills copy': typeof ItSkillscopyRoute
  '/online-safety': typeof OnlineSafetyRouteWithChildren
  '/hardware-software/input-output': typeof HardwareSoftwareInputOutputRoute
  '/it-skills/file-simulation': typeof ItSkillsFileSimulationRoute
  '/it-skills/mouse-skills': typeof ItSkillsMouseSkillsRoute
  '/online-safety/phishing': typeof OnlineSafetyPhishingRoute
  '/online-safety/social-credit': typeof OnlineSafetySocialCreditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algorithms'
    | '/it-skills'
    | '/it-skills copy'
    | '/online-safety'
    | '/hardware-software/input-output'
    | '/it-skills/file-simulation'
    | '/it-skills/mouse-skills'
    | '/online-safety/phishing'
    | '/online-safety/social-credit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algorithms'
    | '/it-skills'
    | '/it-skills copy'
    | '/online-safety'
    | '/hardware-software/input-output'
    | '/it-skills/file-simulation'
    | '/it-skills/mouse-skills'
    | '/online-safety/phishing'
    | '/online-safety/social-credit'
  id:
    | '__root__'
    | '/'
    | '/algorithms'
    | '/it-skills'
    | '/it-skills copy'
    | '/online-safety'
    | '/hardware-software/input-output'
    | '/it-skills/file-simulation'
    | '/it-skills/mouse-skills'
    | '/online-safety/phishing'
    | '/online-safety/social-credit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmsRoute: typeof AlgorithmsRoute
  ItSkillsRoute: typeof ItSkillsRouteWithChildren
  ItSkillscopyRoute: typeof ItSkillscopyRoute
  OnlineSafetyRoute: typeof OnlineSafetyRouteWithChildren
  HardwareSoftwareInputOutputRoute: typeof HardwareSoftwareInputOutputRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/online-safety': {
      id: '/online-safety'
      path: '/online-safety'
      fullPath: '/online-safety'
      preLoaderRoute: typeof OnlineSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-skills copy': {
      id: '/it-skills copy'
      path: '/it-skills copy'
      fullPath: '/it-skills copy'
      preLoaderRoute: typeof ItSkillscopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-skills': {
      id: '/it-skills'
      path: '/it-skills'
      fullPath: '/it-skills'
      preLoaderRoute: typeof ItSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms': {
      id: '/algorithms'
      path: '/algorithms'
      fullPath: '/algorithms'
      preLoaderRoute: typeof AlgorithmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-safety/social-credit': {
      id: '/online-safety/social-credit'
      path: '/social-credit'
      fullPath: '/online-safety/social-credit'
      preLoaderRoute: typeof OnlineSafetySocialCreditRouteImport
      parentRoute: typeof OnlineSafetyRoute
    }
    '/online-safety/phishing': {
      id: '/online-safety/phishing'
      path: '/phishing'
      fullPath: '/online-safety/phishing'
      preLoaderRoute: typeof OnlineSafetyPhishingRouteImport
      parentRoute: typeof OnlineSafetyRoute
    }
    '/it-skills/mouse-skills': {
      id: '/it-skills/mouse-skills'
      path: '/mouse-skills'
      fullPath: '/it-skills/mouse-skills'
      preLoaderRoute: typeof ItSkillsMouseSkillsRouteImport
      parentRoute: typeof ItSkillsRoute
    }
    '/it-skills/file-simulation': {
      id: '/it-skills/file-simulation'
      path: '/file-simulation'
      fullPath: '/it-skills/file-simulation'
      preLoaderRoute: typeof ItSkillsFileSimulationRouteImport
      parentRoute: typeof ItSkillsRoute
    }
    '/hardware-software/input-output': {
      id: '/hardware-software/input-output'
      path: '/hardware-software/input-output'
      fullPath: '/hardware-software/input-output'
      preLoaderRoute: typeof HardwareSoftwareInputOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ItSkillsRouteChildren {
  ItSkillsFileSimulationRoute: typeof ItSkillsFileSimulationRoute
  ItSkillsMouseSkillsRoute: typeof ItSkillsMouseSkillsRoute
}

const ItSkillsRouteChildren: ItSkillsRouteChildren = {
  ItSkillsFileSimulationRoute: ItSkillsFileSimulationRoute,
  ItSkillsMouseSkillsRoute: ItSkillsMouseSkillsRoute,
}

const ItSkillsRouteWithChildren = ItSkillsRoute._addFileChildren(
  ItSkillsRouteChildren,
)

interface OnlineSafetyRouteChildren {
  OnlineSafetyPhishingRoute: typeof OnlineSafetyPhishingRoute
  OnlineSafetySocialCreditRoute: typeof OnlineSafetySocialCreditRoute
}

const OnlineSafetyRouteChildren: OnlineSafetyRouteChildren = {
  OnlineSafetyPhishingRoute: OnlineSafetyPhishingRoute,
  OnlineSafetySocialCreditRoute: OnlineSafetySocialCreditRoute,
}

const OnlineSafetyRouteWithChildren = OnlineSafetyRoute._addFileChildren(
  OnlineSafetyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmsRoute: AlgorithmsRoute,
  ItSkillsRoute: ItSkillsRouteWithChildren,
  ItSkillscopyRoute: ItSkillscopyRoute,
  OnlineSafetyRoute: OnlineSafetyRouteWithChildren,
  HardwareSoftwareInputOutputRoute: HardwareSoftwareInputOutputRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
