/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnlineSafetyRouteImport } from './routes/online-safety'
import { Route as MathsRouteImport } from './routes/maths'
import { Route as ItSkillsRouteImport } from './routes/it-skills'
import { Route as HardwareSoftwareRouteImport } from './routes/hardware-software'
import { Route as AlgorithmsRouteImport } from './routes/algorithms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnlineSafetySocialCreditRouteImport } from './routes/online-safety/social-credit'
import { Route as OnlineSafetyPhishingRouteImport } from './routes/online-safety/phishing'
import { Route as MathsAsciiRouteImport } from './routes/maths/ascii'
import { Route as ItSkillsMouseSkillsRouteImport } from './routes/it-skills/mouse-skills'
import { Route as ItSkillsFilesAndFoldersRouteImport } from './routes/it-skills/files-and-folders'
import { Route as HardwareSoftwareNameHardwareRouteImport } from './routes/hardware-software/name-hardware'
import { Route as HardwareSoftwareInputOutputRouteImport } from './routes/hardware-software/input-output'
import { Route as HardwareSoftwareIdentifySoftwareRouteImport } from './routes/hardware-software/identify-software'

const OnlineSafetyRoute = OnlineSafetyRouteImport.update({
  id: '/online-safety',
  path: '/online-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const MathsRoute = MathsRouteImport.update({
  id: '/maths',
  path: '/maths',
  getParentRoute: () => rootRouteImport,
} as any)
const ItSkillsRoute = ItSkillsRouteImport.update({
  id: '/it-skills',
  path: '/it-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareSoftwareRoute = HardwareSoftwareRouteImport.update({
  id: '/hardware-software',
  path: '/hardware-software',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsRoute = AlgorithmsRouteImport.update({
  id: '/algorithms',
  path: '/algorithms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineSafetySocialCreditRoute =
  OnlineSafetySocialCreditRouteImport.update({
    id: '/social-credit',
    path: '/social-credit',
    getParentRoute: () => OnlineSafetyRoute,
  } as any)
const OnlineSafetyPhishingRoute = OnlineSafetyPhishingRouteImport.update({
  id: '/phishing',
  path: '/phishing',
  getParentRoute: () => OnlineSafetyRoute,
} as any)
const MathsAsciiRoute = MathsAsciiRouteImport.update({
  id: '/ascii',
  path: '/ascii',
  getParentRoute: () => MathsRoute,
} as any)
const ItSkillsMouseSkillsRoute = ItSkillsMouseSkillsRouteImport.update({
  id: '/mouse-skills',
  path: '/mouse-skills',
  getParentRoute: () => ItSkillsRoute,
} as any)
const ItSkillsFilesAndFoldersRoute = ItSkillsFilesAndFoldersRouteImport.update({
  id: '/files-and-folders',
  path: '/files-and-folders',
  getParentRoute: () => ItSkillsRoute,
} as any)
const HardwareSoftwareNameHardwareRoute =
  HardwareSoftwareNameHardwareRouteImport.update({
    id: '/name-hardware',
    path: '/name-hardware',
    getParentRoute: () => HardwareSoftwareRoute,
  } as any)
const HardwareSoftwareInputOutputRoute =
  HardwareSoftwareInputOutputRouteImport.update({
    id: '/input-output',
    path: '/input-output',
    getParentRoute: () => HardwareSoftwareRoute,
  } as any)
const HardwareSoftwareIdentifySoftwareRoute =
  HardwareSoftwareIdentifySoftwareRouteImport.update({
    id: '/identify-software',
    path: '/identify-software',
    getParentRoute: () => HardwareSoftwareRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/hardware-software': typeof HardwareSoftwareRouteWithChildren
  '/it-skills': typeof ItSkillsRouteWithChildren
  '/maths': typeof MathsRouteWithChildren
  '/online-safety': typeof OnlineSafetyRouteWithChildren
  '/hardware-software/identify-software': typeof HardwareSoftwareIdentifySoftwareRoute
  '/hardware-software/input-output': typeof HardwareSoftwareInputOutputRoute
  '/hardware-software/name-hardware': typeof HardwareSoftwareNameHardwareRoute
  '/it-skills/files-and-folders': typeof ItSkillsFilesAndFoldersRoute
  '/it-skills/mouse-skills': typeof ItSkillsMouseSkillsRoute
  '/maths/ascii': typeof MathsAsciiRoute
  '/online-safety/phishing': typeof OnlineSafetyPhishingRoute
  '/online-safety/social-credit': typeof OnlineSafetySocialCreditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/hardware-software': typeof HardwareSoftwareRouteWithChildren
  '/it-skills': typeof ItSkillsRouteWithChildren
  '/maths': typeof MathsRouteWithChildren
  '/online-safety': typeof OnlineSafetyRouteWithChildren
  '/hardware-software/identify-software': typeof HardwareSoftwareIdentifySoftwareRoute
  '/hardware-software/input-output': typeof HardwareSoftwareInputOutputRoute
  '/hardware-software/name-hardware': typeof HardwareSoftwareNameHardwareRoute
  '/it-skills/files-and-folders': typeof ItSkillsFilesAndFoldersRoute
  '/it-skills/mouse-skills': typeof ItSkillsMouseSkillsRoute
  '/maths/ascii': typeof MathsAsciiRoute
  '/online-safety/phishing': typeof OnlineSafetyPhishingRoute
  '/online-safety/social-credit': typeof OnlineSafetySocialCreditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRoute
  '/hardware-software': typeof HardwareSoftwareRouteWithChildren
  '/it-skills': typeof ItSkillsRouteWithChildren
  '/maths': typeof MathsRouteWithChildren
  '/online-safety': typeof OnlineSafetyRouteWithChildren
  '/hardware-software/identify-software': typeof HardwareSoftwareIdentifySoftwareRoute
  '/hardware-software/input-output': typeof HardwareSoftwareInputOutputRoute
  '/hardware-software/name-hardware': typeof HardwareSoftwareNameHardwareRoute
  '/it-skills/files-and-folders': typeof ItSkillsFilesAndFoldersRoute
  '/it-skills/mouse-skills': typeof ItSkillsMouseSkillsRoute
  '/maths/ascii': typeof MathsAsciiRoute
  '/online-safety/phishing': typeof OnlineSafetyPhishingRoute
  '/online-safety/social-credit': typeof OnlineSafetySocialCreditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algorithms'
    | '/hardware-software'
    | '/it-skills'
    | '/maths'
    | '/online-safety'
    | '/hardware-software/identify-software'
    | '/hardware-software/input-output'
    | '/hardware-software/name-hardware'
    | '/it-skills/files-and-folders'
    | '/it-skills/mouse-skills'
    | '/maths/ascii'
    | '/online-safety/phishing'
    | '/online-safety/social-credit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algorithms'
    | '/hardware-software'
    | '/it-skills'
    | '/maths'
    | '/online-safety'
    | '/hardware-software/identify-software'
    | '/hardware-software/input-output'
    | '/hardware-software/name-hardware'
    | '/it-skills/files-and-folders'
    | '/it-skills/mouse-skills'
    | '/maths/ascii'
    | '/online-safety/phishing'
    | '/online-safety/social-credit'
  id:
    | '__root__'
    | '/'
    | '/algorithms'
    | '/hardware-software'
    | '/it-skills'
    | '/maths'
    | '/online-safety'
    | '/hardware-software/identify-software'
    | '/hardware-software/input-output'
    | '/hardware-software/name-hardware'
    | '/it-skills/files-and-folders'
    | '/it-skills/mouse-skills'
    | '/maths/ascii'
    | '/online-safety/phishing'
    | '/online-safety/social-credit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmsRoute: typeof AlgorithmsRoute
  HardwareSoftwareRoute: typeof HardwareSoftwareRouteWithChildren
  ItSkillsRoute: typeof ItSkillsRouteWithChildren
  MathsRoute: typeof MathsRouteWithChildren
  OnlineSafetyRoute: typeof OnlineSafetyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/online-safety': {
      id: '/online-safety'
      path: '/online-safety'
      fullPath: '/online-safety'
      preLoaderRoute: typeof OnlineSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maths': {
      id: '/maths'
      path: '/maths'
      fullPath: '/maths'
      preLoaderRoute: typeof MathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-skills': {
      id: '/it-skills'
      path: '/it-skills'
      fullPath: '/it-skills'
      preLoaderRoute: typeof ItSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware-software': {
      id: '/hardware-software'
      path: '/hardware-software'
      fullPath: '/hardware-software'
      preLoaderRoute: typeof HardwareSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms': {
      id: '/algorithms'
      path: '/algorithms'
      fullPath: '/algorithms'
      preLoaderRoute: typeof AlgorithmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-safety/social-credit': {
      id: '/online-safety/social-credit'
      path: '/social-credit'
      fullPath: '/online-safety/social-credit'
      preLoaderRoute: typeof OnlineSafetySocialCreditRouteImport
      parentRoute: typeof OnlineSafetyRoute
    }
    '/online-safety/phishing': {
      id: '/online-safety/phishing'
      path: '/phishing'
      fullPath: '/online-safety/phishing'
      preLoaderRoute: typeof OnlineSafetyPhishingRouteImport
      parentRoute: typeof OnlineSafetyRoute
    }
    '/maths/ascii': {
      id: '/maths/ascii'
      path: '/ascii'
      fullPath: '/maths/ascii'
      preLoaderRoute: typeof MathsAsciiRouteImport
      parentRoute: typeof MathsRoute
    }
    '/it-skills/mouse-skills': {
      id: '/it-skills/mouse-skills'
      path: '/mouse-skills'
      fullPath: '/it-skills/mouse-skills'
      preLoaderRoute: typeof ItSkillsMouseSkillsRouteImport
      parentRoute: typeof ItSkillsRoute
    }
    '/it-skills/files-and-folders': {
      id: '/it-skills/files-and-folders'
      path: '/files-and-folders'
      fullPath: '/it-skills/files-and-folders'
      preLoaderRoute: typeof ItSkillsFilesAndFoldersRouteImport
      parentRoute: typeof ItSkillsRoute
    }
    '/hardware-software/name-hardware': {
      id: '/hardware-software/name-hardware'
      path: '/name-hardware'
      fullPath: '/hardware-software/name-hardware'
      preLoaderRoute: typeof HardwareSoftwareNameHardwareRouteImport
      parentRoute: typeof HardwareSoftwareRoute
    }
    '/hardware-software/input-output': {
      id: '/hardware-software/input-output'
      path: '/input-output'
      fullPath: '/hardware-software/input-output'
      preLoaderRoute: typeof HardwareSoftwareInputOutputRouteImport
      parentRoute: typeof HardwareSoftwareRoute
    }
    '/hardware-software/identify-software': {
      id: '/hardware-software/identify-software'
      path: '/identify-software'
      fullPath: '/hardware-software/identify-software'
      preLoaderRoute: typeof HardwareSoftwareIdentifySoftwareRouteImport
      parentRoute: typeof HardwareSoftwareRoute
    }
  }
}

interface HardwareSoftwareRouteChildren {
  HardwareSoftwareIdentifySoftwareRoute: typeof HardwareSoftwareIdentifySoftwareRoute
  HardwareSoftwareInputOutputRoute: typeof HardwareSoftwareInputOutputRoute
  HardwareSoftwareNameHardwareRoute: typeof HardwareSoftwareNameHardwareRoute
}

const HardwareSoftwareRouteChildren: HardwareSoftwareRouteChildren = {
  HardwareSoftwareIdentifySoftwareRoute: HardwareSoftwareIdentifySoftwareRoute,
  HardwareSoftwareInputOutputRoute: HardwareSoftwareInputOutputRoute,
  HardwareSoftwareNameHardwareRoute: HardwareSoftwareNameHardwareRoute,
}

const HardwareSoftwareRouteWithChildren =
  HardwareSoftwareRoute._addFileChildren(HardwareSoftwareRouteChildren)

interface ItSkillsRouteChildren {
  ItSkillsFilesAndFoldersRoute: typeof ItSkillsFilesAndFoldersRoute
  ItSkillsMouseSkillsRoute: typeof ItSkillsMouseSkillsRoute
}

const ItSkillsRouteChildren: ItSkillsRouteChildren = {
  ItSkillsFilesAndFoldersRoute: ItSkillsFilesAndFoldersRoute,
  ItSkillsMouseSkillsRoute: ItSkillsMouseSkillsRoute,
}

const ItSkillsRouteWithChildren = ItSkillsRoute._addFileChildren(
  ItSkillsRouteChildren,
)

interface MathsRouteChildren {
  MathsAsciiRoute: typeof MathsAsciiRoute
}

const MathsRouteChildren: MathsRouteChildren = {
  MathsAsciiRoute: MathsAsciiRoute,
}

const MathsRouteWithChildren = MathsRoute._addFileChildren(MathsRouteChildren)

interface OnlineSafetyRouteChildren {
  OnlineSafetyPhishingRoute: typeof OnlineSafetyPhishingRoute
  OnlineSafetySocialCreditRoute: typeof OnlineSafetySocialCreditRoute
}

const OnlineSafetyRouteChildren: OnlineSafetyRouteChildren = {
  OnlineSafetyPhishingRoute: OnlineSafetyPhishingRoute,
  OnlineSafetySocialCreditRoute: OnlineSafetySocialCreditRoute,
}

const OnlineSafetyRouteWithChildren = OnlineSafetyRoute._addFileChildren(
  OnlineSafetyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmsRoute: AlgorithmsRoute,
  HardwareSoftwareRoute: HardwareSoftwareRouteWithChildren,
  ItSkillsRoute: ItSkillsRouteWithChildren,
  MathsRoute: MathsRouteWithChildren,
  OnlineSafetyRoute: OnlineSafetyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
